### ISSUE TITLE
Adding expected rank 

### ISSUE THREAD

**Issue by khushit-shah** [snooze6214/GateAnswerExtension#1]
We can send the calculated score to the server and calculate the expected rank.

Some things to take care of:
- Check if HTML is not altered! (Just the table values are not altered)
- A way to uniquely identify a user.

I will try to write a quick  server that accepts {marks, user_id} and returns the expected rank

**Comment by snooze6214** [comment]
if you can do that, that would be great, thanks <3, altho GO's rank predictor will be up tomorrow so :')

**Comment by khushit-shah** [comment]
I have written the server, need to host it somewhere.. can you recommend any free hosting provider except aws/gcloud/azure/heroku?

**Comment by khushit-shah** [comment]
Go rank predictor will be live soon!
